language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
matrix:
  allow_failures:
    - rvm: 1.9.3
  fast_finish: true